version: '3.8'

services:
  travelapi:
    image: ${DOCKER_REGISTRY-}travelapi
    build:
      context: .
      dockerfile: travelapi/Dockerfile
    ports:
      - "8080:80" 
  mysql_cesupa:
    image: mysql:latest 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: traveldb 
    ports:
      - "3306:3306" 

