version: '3.4'

services:
  travelapi:
    image: ${DOCKER_REGISTRY-}travelapi
    build:
      context: .
      dockerfile: travelapi/Dockerfile
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
